services:
  - type: web
    name: clouddrive-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update